name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install NPM modules 
      run: npm install

    - name: Replace the Back-End config
      run: echo "export const settings = {host:\"https://localhost:3000\"}" > src/config.js
      
    - name: Start Back-End
      run: npm run server &
      
    - name: Start Front-End
      run: npm run start &
    
    - name: Install Browsers
      run: npx playwright install
    
    - name: Execute UI tests
      run: npm run test
  
  deploy-BE:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID_BACKEND }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}

  deploy-FE:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID_FRONTEND }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}